version: '3.9'

services:
  mysql-optimum-db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
  optimum-art:
    container_name: optimum-art
    image: img-optimum-art:0.0.1
    build: .
    ports: 
    - 8080:8080
    depends_on:
    - mysql-optimum-db
    volumes:
      - ./target:/app
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-optimum-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080       
volumes:
  db:
  target:
    
      
  
      
    